# Generated by Django 3.0.7 on 2020-06-15 10:44
import os
import json
from django.db import migrations


def ingest_movies_data(apps, schema_editor):
    data_folder = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..", "gv_cinema_app", "data")
    )
    movies_file_path = os.path.join(data_folder, "movies.json")
    # Models
    Movies = apps.get_model('movies', 'Movies')
    Genre = apps.get_model('movies', 'Genre')
    Language = apps.get_model('movies', 'Language')

    file_data = open(movies_file_path)
    movies_data = json.load(file_data)

    for movie_data in movies_data:
        language, is_created = Language.objects.get_or_create(title=movie_data['language'])
        movie_obj = Movies.objects.create(
            name=movie_data['name'],
            description=movie_data['description'],
            image_path=movie_data['imgPath'],
            duration=movie_data['duration'],
            mpaa_rating=movie_data['mpaaRating'],
            user_rating=movie_data['userRating'],
            language=language
        )

        for genre in movie_data['genre']:
            db_genre, is_created = Genre.objects.get_or_create(title=genre)
            movie_obj.genre.add(db_genre)


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ingest_movies_data)
    ]
